// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Defra.UI.Tests.Feature.Regression.Exporter.E2E
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("EHCE2E_ALL")]
    public partial class EHCE2E_ALLFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "EHCE2E.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/Regression/Exporter/E2E", "EHCE2E_ALL", "As a Defra customer, I am able to create and submit a new application", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create and submit a new EHC application")]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8361", "EHC8361", "030231", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8361", "EHC8361", "030231", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8305", "EHC8305", "230910", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8368", "EHC8368", "020210", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8369", "EHC8369", "02068099", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8324", "EHC8324", "230910", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8350", "EHC8350", "151710", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8325", "EHC8325", "230910", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8461", "EHC8461", "1501", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8333", "EHC8333", "230910", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8328", "EHC8328", "41019000", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8370", "EHC8370", "1501", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8364", "EHC8364", "03089010", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8371", "EHC8371", "020713", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8390", "EHC8390", "3503", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8391", "EHC8391", "04090000", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8383", "EHC8383", "160100", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8385", "EHC8385", "160232", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8467", "EHC8467", "040690", null)]
        [NUnit.Framework.TestCaseAttribute("exporter", "automationE2E8435", "EHC8435", "0105120", null)]
        public void CreateAndSubmitANewEHCApplication(string logininfo, string reference, string eHCNumber, string commodityNumber, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("logininfo", logininfo);
            argumentsOfScenario.Add("reference", reference);
            argumentsOfScenario.Add("EHCNumber", eHCNumber);
            argumentsOfScenario.Add("commodityNumber", commodityNumber);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create and submit a new EHC application", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 testRunner.Given("that I navigate to the DEFRA application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 7
 testRunner.And(string.Format("sign in with valid credentials with logininfo \'{0}\'", logininfo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 8
 testRunner.And(string.Format("check the user is \'{0}\'", logininfo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
 testRunner.And("application page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.When("start a new application and click start now", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
 testRunner.And(string.Format("enter a unique application reference \'{0}\' and continue", reference), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
 testRunner.And(string.Format("select certificate for your export \'{0}\' and continue", eHCNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 13
 testRunner.And(string.Format("select commodity \'{0}\' and continue", commodityNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 14
 testRunner.And(string.Format("add \'{0}\' data and submit", eHCNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
 testRunner.Then(string.Format("verify certificate \'{0}\' has been added successfully", reference), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
