trigger:
- master
- dev
- feature/*
- task/*
- release/*

pool:
    name: 'DEFRA-TRD'

variables:
  BuildConfiguration: Release

steps:

  - task: DotNetCoreCLI@2
    displayName: Restore for $(BuildConfiguration)
    inputs:
      command: restore
      projects: '**/Defra.UI.Tests.csproj'
      feedsToUse: 'config'
      includeNuGetOrg: true
      nugetConfigPath: 'nuget.config'
  
  - task: DotNetCoreCLI@2
    displayName: publish for $(BuildConfiguration)
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/Defra.UI.Tests.csproj'
      arguments: --no-restore --configuration $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)

  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'